### PR TITLE
Feat/secret group [wip]

### LINKED ISSUE #31: Feature request: same secret for multiple devices/VMs
### Plugin version

v1.0.5

### netbox-plugin-extensions version

v1.0.2

### NetBox version

v3.0.3

### Feature type

Data model extension

### Proposed functionality

Nowadays we have to add a store a new secret for each device/VM even if all the secrets are the same.
It would be great to be able to assign a secret to multiple devices/VMs (one to many relation).

### Use case

Having and storing the same secret  for many devices is not convenient.

### Database changes

_No response_

### External dependencies

_No response_

### PR DESCRIPTION
**Pull request by abhi1693**
This is the initial draft for adding support for `Secrets Group` which would help in assigning the same set of secrets to multiple devices or virtual machines.

## Current Implementation
So far, I have made minor additions to the existing models like adding an `access_type` and `secret_type` choices to `SecretRole` and `Secret` respectively. The existing implementation is too broad to use with automation tools. So, I have added these choices as a way for such tools to utilise the information in a more standard/formal way. This would also help the user to run better reports and filtering on the data.

I have added the `SecretsGroup` model with M2M on the `Secret` with other basic fields for the user. 

Fixes #31 

## Things to-do
- [ ] Connect `SecretsGroup` with devices and virtual machine
- [ ] Improve the templates for the user

## Things to discuss
1. Should the direct relation between `Secret` and `device/vm` be removed?
2. Should the `name` fields be dropped in favour of `access_type` and `secret_type` fields? These seem redundant to me.

### CODE REVIEW

**Comment by Dees7** [comment]
Good job. But i can't use it. 
I have done migration but looks like some tables don't created.
Please help.
```
<class 'django.db.utils.ProgrammingError'>

relation "netbox_secretstore_secretsgroup" does not exist
LINE 1: SELECT (1) AS "a" FROM "netbox_secretstore_secretsgroup" WHE...
                               ^


Python version: 3.8.10
NetBox version: 3.1.1

```

**Comment by abhi1693** [comment]
@Dees7 this is still a work in progress. I'll be pushing a few more commits to this branch this week

**Comment by DanSheps** [comment]
#31 is limited to assignment of secrets to multiple devices.  Please keep the scope of any FR to that specific scope please.  We will not be adding in any additional functionality (secret type, access type, etc)

**Comment by abhi1693** [comment]
@DanSheps The work was not just to close #31 but to enhance the functionality of the plugin a lot more. But if the plugin is not going to add additional functionality, it seems only useful for people using it manually. We want to have automation tools use this plugin in a more standardized way which is easier for the operators of the net box to improve their pain of documenting the infrastructure.
We have given the current implementation a thorough test run and the effort to implement custom tools is too much. For example, under `SecretRole` a user can write `SSH`, `ssH Logins`, `Credential for SSH` etc. Implementing the tool on such slugs is very difficult but if a type is to be introduced, then it's a piece of cake from thereon. No matter what the user types, the tool knows what the role is all about.

**Pull request closed without merging**
